# Generated by Django 4.1.5 on 2023-01-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Systemevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.BigIntegerField(blank=True, null=True)),
                ('receivedat', models.DateTimeField(blank=True, null=True)),
                ('devicereportedtime', models.DateTimeField(blank=True, null=True)),
                ('facility', models.SmallIntegerField(blank=True, null=True)),
                ('priority', models.SmallIntegerField(blank=True, null=True)),
                ('fromhost', models.CharField(blank=True, max_length=60, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('ntseverity', models.IntegerField(blank=True, null=True)),
                ('importance', models.IntegerField(blank=True, null=True)),
                ('eventsource', models.CharField(blank=True, max_length=60, null=True)),
                ('eventuser', models.CharField(blank=True, max_length=60, null=True)),
                ('eventcategory', models.IntegerField(blank=True, null=True)),
                ('eventid', models.IntegerField(blank=True, null=True)),
                ('eventbinarydata', models.TextField(blank=True, null=True)),
                ('maxavailable', models.IntegerField(blank=True, null=True)),
                ('currusage', models.IntegerField(blank=True, null=True)),
                ('minusage', models.IntegerField(blank=True, null=True)),
                ('maxusage', models.IntegerField(blank=True, null=True)),
                ('infounitid', models.IntegerField(blank=True, null=True)),
                ('syslogtag', models.CharField(blank=True, max_length=60, null=True)),
                ('eventlogtype', models.CharField(blank=True, max_length=60, null=True)),
                ('genericfilename', models.CharField(blank=True, max_length=60, null=True)),
                ('systemid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'systemevents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Systemeventsproperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemeventid', models.IntegerField(blank=True, null=True)),
                ('paramname', models.CharField(blank=True, max_length=255, null=True)),
                ('paramvalue', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'systemeventsproperties',
                'managed': False,
            },
        ),
    ]
